# Site settings
title: efficiency is doing things right, effectiveness is doing the right things
email: aurelien@fontaine.mx
tel: +33 (0)6 64 43 35 63
description: > # this means to ignore newlines until "baseurl:"
  Site d'un artisan logiciel (software craftsman) et d'un évangiliste agile qui vous parle de leadership,
  de libération, d'agilité et un peu des pratiques de développeur
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fontainex.mx" # the base hostname & protocol for your site
twitter_username: funkyproject
github_username:  funkyproject

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
